### ISSUE TITLE
As a user, I want to archive an assessment in order to hide the completed assessment.

### ISSUE THREAD

**Issue by NoneNeko** [marcusgeorgievski/prj-team-1#53] opened 2024-04-08 01:00 UTC
Description:
This feature enables users to archive completed assessments (hiding them from the active list) as well as the option to unarchive them by updating the status. The system will set the assessment to archived when the status is set to complete. The archived assessment is still accessible in the archived assessment modal and the user can also change the status of the archived assessment in the editing assessment modal. Redirect the user back to the main assessment dashboard page.

Acceptance Criteria:
- The assessment can be archived by editing the assessment status and setting it to be completed (also works with unarchive by editing the assessment status and setting it to be ongoing).
- The archived assessment should be hidden from the active assessment list and only accessible through the archived assessment modal. 
- The archived assessment information is stored properly. 
- The user will automatically archive the assessment once its status is set to be complete.
- The archiving assessment feature is accessible only if the user is logged in.

Testing Criteria:
- Modal Display and Interaction Testing (ensure it works properly across different browsers, archiving/unarchiving assessment work as intended and is only accessible through archived assessment modal)
- Verify that archived assessment information is saved to the database properly.
- Verify that the archived assessment is integrated with the filtering/sorting assessment.
- Verify that user is redirected back to the main assessment dashboard page after archiving an assessment.

**Comment by lctoye** [comment] 2024-06-17 22:18
Duplicate of #52

**Closed as completed by lctoye** 2024-06-17 22:18 UTC
